title: Hao Sun
tagline: Condensed-matter theory · Orbitronics · Moiré quantum materials
url: https://sunohao.github.io
baseurl: "/sunohao_condensed_physics"
author:
  name: Hao Sun
  email: sun.hao@nus.edu.sg
  orcid: 0000-0000-0000-0000

# Use kramdown/markdown and a clean permalink structure
markdown: kramdown
permalink: pretty

# Plugins supported by GitHub Pages by default
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Defaults to auto-apply the layout
defaults:
  - scope:
      path: ""
    values:
      layout: default
